[CI] Publish Truefoundry chart version 0.4.7

diff --git a/charts/truefoundry/templates/tfy-build/build-workflow-workflow-template.yaml b/charts/truefoundry/templates/tfy-build/build-workflow-workflow-template.yaml
--- a/charts/truefoundry/templates/tfy-build/build-workflow-workflow-template.yaml
+++ b/charts/truefoundry/templates/tfy-build/build-workflow-workflow-template.yaml
@@ -9,6 +9,7 @@ spec:
       "truefoundry.com/buildName":
         expression: workflow.name
   entrypoint: build
+  activeDeadlineSeconds: 5400
   onExit: exit-handler
   arguments:
     parameters:
@@ -115,7 +116,7 @@ spec:
       backoff:
         duration: "30"
         factor: 2
-        maxDuration: "1h"
+        maxDuration: "2h"
     inputs:
       parameters:
         - name: buildSource
@@ -157,104 +158,104 @@ spec:
         rm -f -R ./source-code
 
         if [[ $BUILD_TYPE == "remote" ]]; then
-            REMOTE_URL=$(echo $BUILD_SOURCE | jq -r '.remote_uri')
-            printf "\033[36m[Start]\033[0m Downloading source code from remote source\n"
-            mkdir -p source-code
-            curl -s -o project-files.tar.gz $REMOTE_URL
-            tar -xf project-files.tar.gz -C source-code
-            cd source-code
+          REMOTE_URL=$(echo $BUILD_SOURCE | jq -r '.remote_uri')
+          printf "\033[36m[Start]\033[0m Downloading source code from remote source\n"
+          mkdir -p source-code
+          curl -s -o project-files.tar.gz $REMOTE_URL
+          tar -xf project-files.tar.gz -C source-code
+          cd source-code
         elif [[ $BUILD_TYPE == "git" || $BUILD_TYPE == "github" ]]; then
-            GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
-            GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
+          GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
+          GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
 
-            git config --global url."https://github.com/".insteadOf git@github.com:
-            git config --global url."https://".insteadOf git://
+          git config --global url."https://github.com/".insteadOf git@github.com:
+          git config --global url."https://".insteadOf git://
 
-            # Example of GIT_URL="https://x-access-token:<token>@github.com/user_name/repo_name"
-            # Example of TRIMMED_URL="https://github.com/user_name/repo_name"
+          # Example of GIT_URL="https://x-access-token:<token>@github.com/user_name/repo_name"
+          # Example of TRIMMED_URL="https://github.com/user_name/repo_name"
 
-            TOKEN=$(echo "$GIT_URL" | sed -n 's/.*x-access-token:\([^@]*\).*/\1/p')
-            TRIMMED_URL=$(echo "$GIT_URL" | sed 's~x-access-token:[^@]*@~~')
+          TOKEN=$(echo "$GIT_URL" | sed -n 's/.*x-access-token:\([^@]*\).*/\1/p')
+          TRIMMED_URL=$(echo "$GIT_URL" | sed 's~x-access-token:[^@]*@~~')
 
-            printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
-            
-            # Set auth token
+          printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
+          
+          # Set auth token
 
-            git config --system credential.helper store
-            echo "https://x-access-token:$TOKEN@github.com" > ~/.git-credentials
+          git config --system credential.helper store
+          echo "https://x-access-token:$TOKEN@github.com" > ~/.git-credentials
 
-            git clone --recursive $TRIMMED_URL source-code
-            cd source-code && git reset --hard $GIT_REF
+          git clone --recursive $TRIMMED_URL source-code
+          cd source-code && git reset --hard $GIT_REF
         elif [[ $BUILD_TYPE == "bitbucket" ]]; then
-            GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
-            GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
+          GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
+          GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
 
-            git config --global url."https://bitbucket.org/".insteadOf git@bitbucket.org:
-            git config --global url."https://".insteadOf git://
+          git config --global url."https://bitbucket.org/".insteadOf git@bitbucket.org:
+          git config --global url."https://".insteadOf git://
 
-            # Example of GIT_URL="https://x-token-auth:<token>@bitbucket.org/user_name/repo_name"
-            # Example of TRIMMED_URL="https://bitbucket.org/user_name/repo_name"
+          # Example of GIT_URL="https://x-token-auth:<token>@bitbucket.org/user_name/repo_name"
+          # Example of TRIMMED_URL="https://bitbucket.org/user_name/repo_name"
 
-            TOKEN=$(echo "$GIT_URL" | sed -n 's/.*x-token-auth:\([^@]*\).*/\1/p')
-            TRIMMED_URL=$(echo "$GIT_URL" | sed 's~x-token-auth:[^@]*@~~')
+          TOKEN=$(echo "$GIT_URL" | sed -n 's/.*x-token-auth:\([^@]*\).*/\1/p')
+          TRIMMED_URL=$(echo "$GIT_URL" | sed 's~x-token-auth:[^@]*@~~')
 
-            printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
-            
-            # Set auth token
+          printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
+          
+          # Set auth token
 
-            git config --system credential.helper store
-            echo "https://x-token-auth:$TOKEN@bitbucket.org" > ~/.git-credentials
+          git config --system credential.helper store
+          echo "https://x-token-auth:$TOKEN@bitbucket.org" > ~/.git-credentials
 
-            git clone --recurse-submodules $TRIMMED_URL source-code
-            cd source-code && git reset --hard $GIT_REF
+          git clone --recurse-submodules $TRIMMED_URL source-code
+          cd source-code && git reset --hard $GIT_REF
         elif [[ $BUILD_TYPE == "gitlab" ]]; then
-            GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
-            GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
+          GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
+          GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
 
-            git config --global url."https://gitlab.com/".insteadOf git@gitlab.com:
-            git config --global url."https://".insteadOf git://
+          git config --global url."https://gitlab.com/".insteadOf git@gitlab.com:
+          git config --global url."https://".insteadOf git://
 
-            # Example of GIT_URL="https://oauth2:<token>@gitlab.com/user_name/repo_name"
-            # Example of TRIMMED_URL="https://gitlab.com/user_name/repo_name"
+          # Example of GIT_URL="https://oauth2:<token>@gitlab.com/user_name/repo_name"
+          # Example of TRIMMED_URL="https://gitlab.com/user_name/repo_name"
 
-            TOKEN=$(echo "$GIT_URL" | sed -n 's/.*oauth2:\([^@]*\).*/\1/p')
-            TRIMMED_URL=$(echo "$GIT_URL" | sed 's~oauth2:[^@]*@~~')
+          TOKEN=$(echo "$GIT_URL" | sed -n 's/.*oauth2:\([^@]*\).*/\1/p')
+          TRIMMED_URL=$(echo "$GIT_URL" | sed 's~oauth2:[^@]*@~~')
 
-            printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
-            
-            # Set auth token
+          printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
+          
+          # Set auth token
 
-            git config --system credential.helper store
-            echo "https://oauth2:$TOKEN@gitlab.com" > ~/.git-credentials
+          git config --system credential.helper store
+          echo "https://oauth2:$TOKEN@gitlab.com" > ~/.git-credentials
 
-            git clone --recurse-submodules $TRIMMED_URL source-code
-            cd source-code && git reset --hard $GIT_REF
+          git clone --recurse-submodules $TRIMMED_URL source-code
+          cd source-code && git reset --hard $GIT_REF
         elif [[ $BUILD_TYPE == "azure" ]]; then
-            GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
-            GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
+          GIT_URL=$(echo $BUILD_SOURCE | jq -r '.repo_url')
+          GIT_REF=$(echo $BUILD_SOURCE | jq -r '.ref')
 
-            git config --global url."https://dev.azure.com/".insteadOf git@ssh.dev.azure.com:v3/
-            git config --global url."https://".insteadOf git://
+          git config --global url."https://dev.azure.com/".insteadOf git@ssh.dev.azure.com:v3/
+          git config --global url."https://".insteadOf git://
 
-            # Example of GIT_URL="https://x-token-auth:<token>@dev.azure.com/organization/project/_git/repo_name"
-            # Example of TRIMMED_URL="https://dev.azure.com/organization/project/_git/repo_name"
+          # Example of GIT_URL="https://x-token-auth:<token>@dev.azure.com/organization/project/_git/repo_name"
+          # Example of TRIMMED_URL="https://dev.azure.com/organization/project/_git/repo_name"
 
-            TOKEN=$(echo "$GIT_URL" | sed -n 's/.*x-token-auth:\([^@]*\).*/\1/p')
-            TRIMMED_URL=$(echo "$GIT_URL" | sed 's~x-token-auth:[^@]*@~~')
+          TOKEN=$(echo "$GIT_URL" | sed -n 's/.*x-token-auth:\([^@]*\).*/\1/p')
+          TRIMMED_URL=$(echo "$GIT_URL" | sed 's~x-token-auth:[^@]*@~~')
 
-            printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
-            
-            # Set auth token
-            git config --system credential.helper store
-            echo "https://x-token-auth:$TOKEN@dev.azure.com" > ~/.git-credentials
+          printf "\033[36m[Start]\033[0m Downloading source code from $TRIMMED_URL\n"
+          
+          # Set auth token
+          git config --system credential.helper store
+          echo "https://x-token-auth:$TOKEN@dev.azure.com" > ~/.git-credentials
 
-            git clone --recurse-submodules $TRIMMED_URL source-code
-            cd source-code && git reset --hard $GIT_REF
+          git clone --recurse-submodules $TRIMMED_URL source-code
+          cd source-code && git reset --hard $GIT_REF
         elif [[ $BUILD_TYPE == "notebook_build" ]]; then
-            :
+          :
         else
-            printf "{{ .Values.tfyBuild.truefoundryWorkflows.logMarkers.error }} Source type '$BUILD_TYPE' not supported.\n"
-            exit 1
+          printf "{{ .Values.tfyBuild.truefoundryWorkflows.logMarkers.error }} Source type '$BUILD_TYPE' not supported.\n"
+          exit 1
         fi
         printf "{{ .Values.tfyBuild.truefoundryWorkflows.logMarkers.done }} Download code completed\n"
         printf "\033[36m[Start]\033[0m Building and pushing the docker container. Please find the logs below\n"
@@ -264,6 +265,17 @@ spec:
         docker login -u "{{`{{inputs.parameters.dockerRegistryUsername}}`}}" -p $DOCKER_PASSWORD "{{`{{inputs.parameters.dockerRegistryURL}}`}}" 2>&1 || { echo "Error: Docker login failed, make sure your authentication credentials are correct in registry!" >&2; exit 1; }
         
         IMAGE="{{`{{inputs.parameters.dockerRegistryURL}}`}}"/"{{`{{inputs.parameters.dockerRepo}}`}}"
+
+        # Split buildkitServiceURL into host and port
+        IFS=':' read -r -a BUILDKIT_SERVICE_URL_PARTS <<< "{{`{{inputs.parameters.buildkitServiceURL}}`}}"
+        BUILDKIT_HOST="${BUILDKIT_SERVICE_URL_PARTS[0]}"
+        BUILDKIT_PORT="${BUILDKIT_SERVICE_URL_PARTS[1]}"
+
+        # Test connectivity using nc (netcat) with a timeout of 2 minutes
+        if ! nc -z -w 120 "$BUILDKIT_HOST" "$BUILDKIT_PORT"; then
+          echo "Error: Unable to connect to buildkit service at $BUILDKIT_HOST:$BUILDKIT_PORT"
+          exit 1
+        fi
         
         printf "\033[36m[==== Docker logs start ====]\033[0m\n"
         docker buildx create --name remote-kubernetes --driver remote tcp://{{`{{inputs.parameters.buildkitServiceURL}}`}}
